<?php

return [
    'landing_base_url' => 'https://archerchessacademy.com',

    'landing_pages' => [
        ['label' => 'India', 'path' => '/online-chess/india'],
        ['label' => 'USA', 'path' => '/online-chess/usa'],
        ['label' => 'Middle East', 'path' => '/online-chess/middle-east'],
        ['label' => 'Singapore', 'path' => '/online-chess/singapore'],
        ['label' => 'UAE', 'path' => '/online-chess/uae'],
        ['label' => 'United Kingdom', 'path' => '/online-chess/united-kingdom'],
        ['label' => 'Australia', 'path' => '/online-chess/australia'],
        ['label' => 'Canada', 'path' => '/online-chess/canada'],
        ['label' => 'New Zealand', 'path' => '/online-chess/new-zealand'],
        ['label' => 'European Union', 'path' => '/online-chess/european-union'],
    ],

    'countries' => [
        'USA' => [
            'label' => 'USA',
            'dial_code' => '+1',
            'currency' => 'USD',
            'payment_column' => 'usa_fees',
            'timezones' => [
                'Eastern Daylight Time',
                'Central Daylight Time',
                'Mountain Daylight Time',
                'Pacific Daylight Time',
                'Alaska Daylight Time',
                'Mountain Standard Time',
                'Eastern Standard Time',
                'Central Standard Time',
                'Pacific Standard Time',
                'Alaska Standard Time',
                'Hawaii-Aleutian Standard Time',
                'Hawaii-Aleutian Daylight Time',
            ],
        ],
        'CANADA' => [
            'label' => 'CANADA',
            'dial_code' => '+1',
            'currency' => 'CAD',
            'payment_column' => 'canada_fees',
            'timezones' => [
                'Eastern Daylight Time',
                'Central Daylight Time',
                'Mountain Daylight Time',
                'Pacific Daylight Time',
                'Alaska Daylight Time',
                'Mountain Standard Time',
                'Eastern Standard Time',
                'Central Standard Time',
                'Pacific Standard Time',
                'Alaska Standard Time',
                'Hawaii-Aleutian Standard Time',
                'Hawaii-Aleutian Daylight Time',
            ],
        ],
        'AUSTRALIA' => [
            'label' => 'AUSTRALIA',
            'dial_code' => '+61',
            'currency' => 'AUD',
            'payment_column' => 'australia_fees',
            'timezones' => ['Australia/Perth', 'Australia/Darwin', 'Australia/Brisbane', 'Australia/Adelaide', 'Australia/Sydney'],
        ],
        'NEWZEALAND' => [
            'label' => 'NEW ZEALAND',
            'dial_code' => '+64',
            'currency' => 'NZD',
            'payment_column' => 'newzealand_fees',
            'timezones' => ['New Zealand Daylight Time', 'New Zealand Standard Time'],
        ],
        'INDIA' => [
            'label' => 'INDIA',
            'dial_code' => '+91',
            'currency' => 'INR',
            'payment_column' => 'india_fees',
            'timezones' => ['Indian Standard Time'],
        ],
        'UAE' => [
            'label' => 'UAE',
            'dial_code' => '+971',
            'currency' => 'AED',
            'payment_column' => 'uae_fees',
            'timezones' => ['Gulf Standard Time'],
        ],
        'UK' => [
            'label' => 'UK',
            'dial_code' => '+44',
            'currency' => 'GBP',
            'payment_column' => 'uk_fees',
            'timezones' => ['British Summer Time', 'Greenwich Mean Time'],
        ],
        'QATAR' => [
            'label' => 'QATAR',
            'dial_code' => '+974',
            'currency' => 'QAR',
            'payment_column' => 'qatar_fees',
            'timezones' => ['Arabian Standard Time'],
        ],
        'SINGAPORE' => [
            'label' => 'SINGAPORE',
            'dial_code' => '+65',
            'currency' => 'SGD',
            'payment_column' => 'singapore_fees',
            'timezones' => ['Singapore Standard Time'],
        ],
        'MALAYSIA' => [
            'label' => 'MALAYSIA',
            'dial_code' => '+60',
            'currency' => 'MYR',
            'payment_column' => 'malaysia_fees',
            'timezones' => ['Malaysia Time'],
        ],
        'HONG KONG' => [
            'label' => 'HONG KONG',
            'dial_code' => '+852',
            'currency' => 'HKD',
            'payment_column' => 'hong_kong_fees',
            'timezones' => ['Hong Kong Standard Time'],
        ],
        'SOUTH AFRICA' => [
            'label' => 'SOUTH AFRICA',
            'dial_code' => '+27',
            'currency' => 'ZAR',
            'payment_column' => 'south_africa_fees',
            'timezones' => ['South Africa Standard Time'],
        ],
        'EUROPEAN UNION' => [
            'label' => 'EUROPEAN UNION',
            'dial_code' => '+358',
            'currency' => 'EUR',
            'payment_column' => 'european_union_fees',
            'timezones' => ['Central European Time', 'Eastern European Time', 'Western European Time'],
        ],
        'OMAN' => [
            'label' => 'OMAN',
            'dial_code' => '+968',
            'currency' => 'OMR',
            'payment_column' => 'oman_fees',
            'timezones' => ['Gulf Standard Time'],
        ],
        'KUWAIT' => [
            'label' => 'KUWAIT',
            'dial_code' => '+965',
            'currency' => 'KWD',
            'payment_column' => 'kuwait_fees',
            'timezones' => ['Arabian Standard Time'],
        ],
        'BAHRAIN' => [
            'label' => 'BAHRAIN',
            'dial_code' => '+973',
            'currency' => 'BHD',
            'payment_column' => 'bahrain_fees',
            'timezones' => ['Arabian Standard Time'],
        ],
        'SAUDI ARABIA' => [
            'label' => 'SAUDI ARABIA',
            'dial_code' => '+966',
            'currency' => 'SAR',
            'payment_column' => 'saudi_arabia_fees',
            'timezones' => ['Arabian Standard Time'],
        ],
    ],
];
